### ⚠️ Important Note Before You Start!
**Please, DO NOT use AI (ChatGPT, Claude, Gemini, etc.) to solve these exercises**
- if you don't struggle a bit with the data.. try things.. and get a few errors along the way you won't actually learn anything
- The whole point of this track is to build your own Engineering Sense with data
- If you just Copy & Paste you’re only cheating yourself out of the real experience
- So take your time... look at the data... rewatch the parts you missed in videos and try to build the logic yourself

# Getting and Knowing your Data

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset & Assign it to a variable called chipo.

In [2]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep='\t')

### Step 4. See the first 10 entries

In [3]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of columns in the dataset?

In [4]:
print(chipo.shape[1])

5

### Step 6. Print a summary of the DataFrame

In [5]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

### Step 7. Print the name of all the columns.

In [6]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Step 8.Display only the item_name column.

In [7]:
chipo['item_name']

0                Chips and Fresh Tomato Salsa
1                                        Izze
2                            Nantucket Nectar
3       Chips and Tomatillo-Green Chili Salsa
4                                Chicken Bowl
                        ...
4617                            Steak Burrito
4618                            Steak Burrito
4619                       Chicken Salad Bowl
4620                       Chicken Salad Bowl
4621                       Chicken Salad Bowl
Name: item_name, Length: 4622, dtype: object

### Step 9. Use `.loc` to display the first 5 rows for only two columns: item_name and item_price

In [8]:
chipo.loc[0:4, ['item_name', 'item_price']]

                               item_name item_price
0           Chips and Fresh Tomato Salsa     $2.39
1                                   Izze     $3.39
2                       Nantucket Nectar     $3.39
3  Chips and Tomatillo-Green Chili Salsa     $2.39
4                           Chicken Bowl    $16.98

### Step 10. Sort by the name of the item

In [9]:
chipo.sort_values(by='item_name')

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],$12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],$6.49
1849,749,1,6 Pack Soft Drink,[Coke],$6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],$6.49
2713,1076,1,6 Pack Soft Drink,[Coke],$6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",$8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49

### Step 11. Which was the most-ordered item?

In [10]:
c = chipo.groupby('item_name').sum()
c = c.sort_values(['quantity'], ascending=False)
c.head(1)

,order_id,quantity,choice_description,item_price
item_name,,,,
Chicken Bowl,713926,761,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98 $10.98 $11.25 $8.75 $8.49 $11.25 $8.75 ...

### Step 12. For the most-ordered item, how many items were ordered?

In [11]:
c = chipo.groupby('item_name').sum()
c = c.sort_values(['quantity'], ascending=False)
c.head(1)['quantity']

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

### Step 13. What was the most ordered item in the choice_description column?

In [12]:
c = chipo.groupby('choice_description').sum()
c = c.sort_values(['quantity'], ascending=False)
c.head(1)

,order_id,quantity,item_name,item_price
choice_description,,,,
[Diet Coke],123455,159,Canned SodaCanned SodaCanned Soda6 Pack Soft D...,$2.18 $1.09 $1.09 $6.49 $2.18 $1.25 $1.09 $6.4...

### Step 14. How many items were orderd in total?

In [13]:
total_items_ordered = chipo.quantity.sum()
total_items_ordered

np.int64(4972)

### Step 15. Retrieve all orders where the item_name is exactly 'Chicken Bowl'

### Step 16. Find all orders where the quantity is greater than 2.

In [17]:
chipo[chipo.quantity > 2]

,order_id,quantity,item_name,choice_description,item_price
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
689,284,3,Canned Soft Drink,[Diet Coke],$3.75
818,338,3,Bottled Water,NaN,$3.27
850,350,3,Canned Soft Drink,[Sprite],$3.75
917,379,3,Canned Soft Drink,[Lemonade],$3.75
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$35.00
1255,511,3,Steak Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$27.75
1257,511,4,Chips and Fresh Tomato Salsa,NaN,$11.80
1425,577,4,Bottled Water,NaN,$6.00
1514,616,3,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$26.25
1559,633,3,Canned Soft Drink,[Coke],$3.75
1880,759,4,Bottled Water,NaN,$6.00
2235,901,4,Canned Soda,[Sprite],$4.36
2441,970,5,Bottled Water,NaN,$7.50
2645,1051,3,Chips and Guacamole,NaN,$13.35
2823,1121,3,Bottled Water,NaN,$3.27
2936,1167,3,Chips,NaN,$6.45
2944,1170,3,Side of Chips,NaN,$5.07
2972,1182,3,Chips and Tomatillo-Red Chili Salsa,NaN,$7.17
3089,1231,3,Canned Soft Drink,[Diet Coke],$3.75
3128,1247,3,Canned Soft Drink,[Diet Coke],$3.75
3270,1309,3,Chips and Tomatillo-Red Chili Salsa,NaN,$7.17
3294,1321,3,Bottled Water,NaN,$4.50
3314,1328,3,Bottled Water,NaN,$4.50
3334,1336,3,Steak Bowl,"[Tomatillo Green Chili (Medium), [Rice, Black ...",$26.07
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$35.25
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25
3599,1443,7,Bottled Water,NaN,$10.50
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$33.75
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$35.00
3603,1443,3,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$27.75
3634,1454,3,Chicken Burrito,[Fresh Tomato Salsa],$26.25
3636,1454,3,Chicken Burrito,"[Fresh Tomato Salsa, Rice]",$26.25
3887,1559,8,Side of Chips,NaN,$13.52
3973,1592,4,Canned Soft Drink,[Coke],$5.00
4098,1642,3,Canned Soft Drink,[Diet Coke],$3.75
4137,1655,3,Bottled Water,NaN,$4.50
4152,1660,10,Bottled Water,NaN,$15.00
4186,1671,3,Bottled Water,NaN,$4.50
4489,1786,4,Chips and Guacamole,NaN,$17.80
4490,1786,4,Canned Soft Drink,[Coke],$5.00
4491,1786,4,Canned Soft Drink,[Sprite],$5.00

### Step 17. How many products cost more than $10.00?

In [18]:
# أولاً: بنشيل علامة الـ $ ونحول السعر لرقم (float)
chipo['item_price'] = chipo['item_price'].apply(lambda x: float(x[1:-1]))

# ثانياً: بنفلتر ونحسب العدد
products_over_10 = chipo[chipo['item_price'] > 10]
print(len(products_over_10))

1130

### Step 18.Set the order_id column as the index of your DataFrame.

In [19]:
chipo.set_index('order_id', inplace=True)

#### 18.a. Display the first 5 rows to see how the new index looks.

In [20]:
chipo.head(5)

,quantity,item_name,choice_description,item_price
order_id,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,Izze,[Clementine],3.39
1,1,Nantucket Nectar,[Apple],3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

#### 18.b. Reset the index back to the default integer index.

In [21]:
chipo.reset_index(inplace=True)

### Step 19. Rename the column item_name to product_name.

In [22]:
chipo.rename(columns={'item_name': 'product_name'}, inplace=True)

### Step 20. Convert all text in the choice_description column to lowercase letters.

In [23]:
chipo['choice_description'] = chipo['choice_description'].str.lower()

### Step 21. Create a new column called is_expensive and set it to True if the price is above 12, and False otherwise.

In [ ]:
chipo['is_expensive'] = chipo['item_price'] > 12

### Step 22. Delete the choice_description column from the DataFrame

In [24]:
chipo.drop(columns=['choice_description'], inplace=True)